// File generated by FlutterFire CLI.
// This file should be version controlled.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFyAAcaIQ2vRLM3OYUU_vItSBquKpnyck',
    appId: '1:69505171248:web:d51cc353d67a9f2e8bd2f5',
    messagingSenderId: '69505171248',
    projectId: 'ecommerce-2d482',
    authDomain: 'ecommerce-2d482.firebaseapp.com',
    storageBucket: 'ecommerce-2d482.appspot.com',
    measurementId: 'G-PK4PB74MCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFyAAcaIQ2vRLM3OYUU_vItSBquKpnyck',
    appId: '1:69505171248:android:YOUR_ANDROID_APP_ID', // Replace with actual
    messagingSenderId: '69505171248',
    projectId: 'ecommerce-2d482',
    storageBucket: 'ecommerce-2d482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyAAcaIQ2vRLM3OYUU_vItSBquKpnyck',
    appId: '1:69505171248:ios:YOUR_IOS_APP_ID', // Replace with actual
    messagingSenderId: '69505171248',
    projectId: 'ecommerce-2d482',
    storageBucket: 'ecommerce-2d482.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );
}